LIVE_TRADING_ENABLED = False
ACCOUNT_BASE_CAPITAL = 100.0
MAX_RISK_PER_TRADE_PCT = 0.01
MAX_POSITION_SIZE_PCT = 0.25
MAX_CONCURRENT_POSITIONS = 4
DAILY_LOSS_CIRCUIT_BREAKER_PCT = 0.05
WEEKLY_LOSS_CIRCUIT_BREAKER_PCT = 0.10
MAX_DRAWDOWN_CIRCUIT_BREAKER_PCT = 0.15