name: Python CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
    - name: Test with pytest
      run: |
        pip install -r requirements.txt pytest pytest-cov pydantic pydantic-settings pyyaml duckdb pandera nltk praw feedparser openbb arch scipy riskfolio-lib cvxpy nautilus_trader vectorbt
        PYTHONPATH=. pytest tests/ -v --cov=src
